# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af82739fdb0192e12a04f856324417a3e90ae9ec0ac1122fb6ea7cfb950d2dd483920c9f81a62426250e0b5470d822e4b5c4c989536f2e1858541d823d6f7e03

test:
  secret_key_base: 38f0df0fdb04505fe34d8c21e6221b00a8fdbb33cb378a223003fe121f5dc78c83db087d7f995f2c79c3f9b22365186b76f66bf6f90b1ec9e38612a9eb0b330f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
